[package]
name = "bench"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = { git = "https://github.com/blockworks-foundation/solana", branch="lite_rpc" }
solana-rpc-client = { git = "https://github.com/blockworks-foundation/solana", branch="lite_rpc" }
log = "0.4.17"
anyhow = "1.0.68"
serde = "1.0.152"
serde_json = "1.0.91"
csv = "1.1.6"
clap = { version = "4.1.4", features = ["derive"] }
tokio = { version = "1.25.0", features = ["full", "fs"]} 
tracing-subscriber = "0.3.16"
dirs = "4.0.0"
