app = "solana-lite-rpc-benchrunner"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "../Dockerfile-benchrunner"

[env]
  RUST_LOG = "info"

[metrics]
  path = "/metrics"
  port = 9091
